<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.azusachino.flos</groupId>
    <artifactId>flos</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <artifactId>flink</artifactId>
  <packaging>pom</packaging>
  <modules>
    <module>operators</module>
    <module>operator-lab</module>
    <module>event-time</module>
    <module>event-time-lab</module>
    <module>checkpoint-recovery-lab</module>
    <module>pipeline-lab</module>
    <module>state-ttl-lab</module>
    <module>restart-strategy-lab</module>
    <module>slot-sharing-lab</module>
  </modules>
</project>
