apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flos-session
spec:
  image: flink:2.2.1-scala_2.12-java17
  flinkVersion: v2_2
  serviceAccount: flink
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
